var annotated_dup =
[
    [ "MYBAsyncStatusCmd_t", "struct_m_y_b_async_status_cmd__t.html", "struct_m_y_b_async_status_cmd__t" ],
    [ "MYBCmdHdr_t", "struct_m_y_b_cmd_hdr__t.html", "struct_m_y_b_cmd_hdr__t" ],
    [ "MYBDataRsp_t", "struct_m_y_b_data_rsp__t.html", "struct_m_y_b_data_rsp__t" ],
    [ "MYBGetStatusCmd_t", "struct_m_y_b_get_status_cmd__t.html", "struct_m_y_b_get_status_cmd__t" ],
    [ "MYBOSALDataRsp_t", "struct_m_y_b_o_s_a_l_data_rsp__t.html", "struct_m_y_b_o_s_a_l_data_rsp__t" ],
    [ "MYBOSALPingRsp_t", "struct_m_y_b_o_s_a_l_ping_rsp__t.html", "struct_m_y_b_o_s_a_l_ping_rsp__t" ],
    [ "MYBOSALSerialPacket_t", "struct_m_y_b_o_s_a_l_serial_packet__t.html", "struct_m_y_b_o_s_a_l_serial_packet__t" ],
    [ "MYBPingCmd_t", "struct_m_y_b_ping_cmd__t.html", "struct_m_y_b_ping_cmd__t" ],
    [ "MYBPingRsp_t", "struct_m_y_b_ping_rsp__t.html", "struct_m_y_b_ping_rsp__t" ],
    [ "MYBReadCmd_t", "struct_m_y_b_read_cmd__t.html", "struct_m_y_b_read_cmd__t" ],
    [ "MYBRspHdr_t", "struct_m_y_b_rsp_hdr__t.html", "struct_m_y_b_rsp_hdr__t" ],
    [ "MYBStatusRsp_t", "struct_m_y_b_status_rsp__t.html", "struct_m_y_b_status_rsp__t" ],
    [ "MYBWriteCmd_t", "struct_m_y_b_write_cmd__t.html", "struct_m_y_b_write_cmd__t" ],
    [ "MyoHandles_t", "struct_myo_handles__t.html", "struct_myo_handles__t" ],
    [ "myohw_classifier_event_t", "structmyohw__classifier__event__t.html", "structmyohw__classifier__event__t" ],
    [ "myohw_command_deep_sleep_t", "structmyohw__command__deep__sleep__t.html", "structmyohw__command__deep__sleep__t" ],
    [ "myohw_command_header_t", "structmyohw__command__header__t.html", "structmyohw__command__header__t" ],
    [ "myohw_command_set_mode_t", "structmyohw__command__set__mode__t.html", "structmyohw__command__set__mode__t" ],
    [ "myohw_command_set_sleep_mode_t", "structmyohw__command__set__sleep__mode__t.html", "structmyohw__command__set__sleep__mode__t" ],
    [ "myohw_command_unlock_t", "structmyohw__command__unlock__t.html", "structmyohw__command__unlock__t" ],
    [ "myohw_command_user_action_t", "structmyohw__command__user__action__t.html", "structmyohw__command__user__action__t" ],
    [ "myohw_command_vibrate2_t", "structmyohw__command__vibrate2__t.html", "structmyohw__command__vibrate2__t" ],
    [ "myohw_command_vibrate_t", "structmyohw__command__vibrate__t.html", "structmyohw__command__vibrate__t" ],
    [ "myohw_emg_data_t", "structmyohw__emg__data__t.html", "structmyohw__emg__data__t" ],
    [ "myohw_fw_info_t", "structmyohw__fw__info__t.html", "structmyohw__fw__info__t" ],
    [ "myohw_fw_version_t", "structmyohw__fw__version__t.html", "structmyohw__fw__version__t" ],
    [ "myohw_imu_data_t", "structmyohw__imu__data__t.html", "structmyohw__imu__data__t" ],
    [ "myohw_motion_event_t", "structmyohw__motion__event__t.html", "structmyohw__motion__event__t" ]
];